### PR TITLE
Krunal readme

### PR DESCRIPTION
**Pull request by KrunalGupta02**
## What type of PR is this? (check all applicable)

- Check according to your PR

- [x] 🚀 Added Profile
- [ ] ✨ Feature Request    
- [ ] ✅ Joined Community
- [ ] 🌟 Stared the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

### CODE REVIEW

**Comment by imaaquibali** [comment]
@KrunalGupta02 I can't see ur changes bro?

**Comment by KrunalGupta02** [comment]
> @KrunalGupta02 I can't see ur changes bro?

Bro by mistake i delete the branch wait i will restore it

**Comment by imaaquibali** [comment]
@ no problem brother :)

**Comment by KrunalGupta02** [comment]
> @ no problem brother :)

Now can u  check

**Comment by imaaquibali** [comment]
can't see 😞

**Comment by KrunalGupta02** [comment]
> can't see 😞
Screenshot 2022-10-23 230400

**Comment by KrunalGupta02** [comment]
@imaaquibali can u check this https://github.com/imaaquibali/awesome-github-profile-readme/pull/79

**Pull request closed without merging**
