### PR TITLE
Please add my readme 

### PR DESCRIPTION
**Pull request by Subhraneel77**
Kindly add my readme for Hacktoberfest 2022

### CODE REVIEW

**Comment by Subhraneel77** [comment]
@imaaquibali Pls add it and label it for Hacktoberfest 2022

**Review by imaaquibali — APPROVED** [review]
LGTM :) Don't forget to ⭐ it man.

**Comment by imaaquibali** [comment]
Thanks for ur contribution brother 🎉

**Comment by Subhraneel77** [comment]
Thank You Sir.

**Pull request merged**
