### PR TITLE
Create ayushsgit.md

### PR DESCRIPTION
**Pull request by ayushsgit**
## What type of PR is this? (check all applicable)

- Check according to your PR

- [x] 🚀 Added Profile
- [ ] ✨ Feature Request    
- [ ] ✅ Joined Community
- [ ] 🌟 Stared the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Added my readme.md file

## Add Link of GitHub Profile
https://github.com/ayushsgit

### CODE REVIEW

**Comment by imaaquibali** [comment]
@ayushsgit please create an issue for this PR :)

**Comment by ayushsgit** [comment]
how to create an issue for this PR?
do i have to close this PR?

**Comment by imaaquibali** [comment]
no,  just go to issue section and click on new issue button .

**Comment by ayushsgit** [comment]
created issue

**Review by imaaquibali — APPROVED** [review]
LGTM 👍

**Comment by ayushsgit** [comment]
😁

**Pull request merged**
